### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by elitewe** [shangqing-liu/GraphSearchNet#1]
How can I find the 'GAT' and 'GCN' folder referenced by src/core/layers/graphs.py？Thanks!

**Comment by xiexieqiqi** [comment]
I also found this problem.

**Comment by zhanghaha1707** [comment]
I also found this problem, did you find a solution?

> How can I find the 'GAT' and 'GCN' folder referenced by src/core/layers/graphs.py？Thanks!

**Comment by shangqing-liu** [comment]
Dear all,

GAT and GCN are not included in this repo. We do not compare with GAT in deep code search.

Thanks

Shangqing
