### ISSUE TITLE
about CAT

### ISSUE THREAD

**Issue by yingweima2022** [shangqing-liu/GraphSearchNet#2]
​Hi, your article "GraphSearchNet: Enhancing GNNs via Capturing Global Dependency for Semantic Code Search" is very inspiring. Thank you very much for your work.

I want to ask you a question. The experimental part is compared with models such as DeepCS and CAT. The CAT model needs to be converted to sbt, but only python ast is officially open source. Can you open source the CAT model of java, etc.?

**Comment by shangqing-liu** [comment]
@193769981 Thanks for your interest in our work. We first convert Java to ast by ourselves. Then we feed the sbt to the official CAT code. So we don't release CAT code since they are officially open source.

**Comment by yingweima2022** [comment]
Thank you for your reply, the CAT official model only converts python's ast to sbt, but there is no java's ast to sbt, how do you convert java's ast to sbt?

**Comment by shangqing-liu** [comment]
We convert it by ourselves.
