### ISSUE TITLE
No graphs built

### ISSUE THREAD

**Issue by fredmarkus** [shangqing-liu/GraphSearchNet#4]
Hello, I am trying to follow your preprocessing steps to build the java graphs. However, without having done any modifications except adjusting the paths to the data directories, I keep getting "valid built 0 graphs totally". I have rechecked the paths to the data directories to confirm that they are correct and I do see the java_funcs directory but I cannot get any graphs to be built successfully. Do you have any suggestions? Is there perhaps some code that has to be adjusted somewhere?

**Comment by shangqing-liu** [comment]
@frede791 Thanks for your attention to our work, I don't know the exact reason why the java graph cannot build. I suggest you check the related java environments that features-javac used.

**Comment by frederik-markus** [comment]
Thank you! I think I have narrowed down the error to the "generate_proto_file function". I've tried running the command variable that is defined in this function separately and it appears that I do not have  the "FeaturePlugin" installed. I did some research online to find out what exactly this plugin is but I could not find any particular reference. Do you have an idea?

**Comment by shangqing-liu** [comment]
You can refer to our paper and we have provided the reference for the used tool.

**Comment by frederik-markus** [comment]
Ok. I think I have managed to fix the error. For future reference, I think it might be quite useful to link to the features-javac repository in the README just to simplify the setup. Thanks again!

**Comment by shangqing-liu** [comment]
Ok, we will update readme, thanks for your suggestions.

**Comment by KellyZhang2020** [comment]
@frede791 @shangqing-liu 
Can you successfully build the java graph？
When i run the `generate_dot_json_file()` function in build_java_graph.py, raise the follow error:
```
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -j
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at uk.ac.cam.acr31.features.javac.dot.GraphToDot.main(GraphToDot.java:38)
```
And in the `https://github.com/acr31/features-javac/blob/511d1baead2be2513baa818fdba1d9effa547c52/dot/src/main/java/uk/ac/cam/acr31/features/javac/dot/GraphToDot.java`  there are three options, as follow, but don't have the option `-j`
```
option.addOption("i", "input-file", true, "Input filename");
option.addOption("o", "output-file", true, "Output filename");
option.addOption("v", "verbose-dot", false, "Verbose dot output");
```
